import Link from "next/link"
import { drywallPath, type DrywallLocale } from "@/lib/drywall-i18n"

export type LegalSection = { title: string; paragraphs?: string[]; bullets?: string[] }

export function LegalPage({ eyebrow, title, intro, sections, locale = "es" }: { eyebrow: string; title: string; intro: string; sections: LegalSection[]; locale?: DrywallLocale }) {
  const otherLocale = locale === "en" ? "es" : "en"
  return <div className="min-h-screen bg-[#f7f8f5] text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6"><Link href={drywallPath(locale, "home")} className="flex items-center gap-2 font-semibold"><span className="grid size-8 place-items-center rounded-lg bg-[#153a31] text-sm text-white">C</span> Cuadrabot</Link><div className="flex items-center gap-3"><Link href={drywallPath(otherLocale, "home")} className="text-xs font-semibold text-slate-600">{otherLocale.toUpperCase()}</Link><Link href={drywallPath(locale, "order")} className="rounded-lg bg-[#e35e38] px-4 py-2 text-sm font-semibold text-white">{locale === "en" ? "Upload plans" : "Subir planos"}</Link></div></div></header><main className="mx-auto max-w-5xl px-4 py-12 sm:px-6 sm:py-16"><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#e35e38]">{eyebrow}</p><h1 className="mt-3 max-w-3xl text-4xl font-semibold tracking-[-0.04em]">{title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-slate-600">{intro}</p><p className="mt-4 text-xs text-slate-400">{locale === "en" ? "Effective 29 August 2026." : "En vigor desde el 29 de agosto de 2026."}</p><div className="mt-10 grid gap-5">{sections.map((section) => <section key={section.title} className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h2 className="text-lg font-semibold">{section.title}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph} className="mt-3 text-sm leading-7 text-slate-600">{paragraph}</p>)}{section.bullets && <ul className="mt-4 space-y-2 pl-5 text-sm leading-6 text-slate-600">{section.bullets.map((bullet) => <li key={bullet} className="list-disc">{bullet}</li>)}</ul>}</section>)}</div></main></div>
}
